name: iRyKits
version: 5.0
main: iRyKits.Main
author: iRyaaNziN
descripition: Plugin iRyKits
commands:
  pvp:
  grandpa:
  cookiemonster:
  snail:
  anchor:
  msg:
  rain:
  viper:
  blackout:
  vis:
  invis:
  skit:
  tempo:
  fake:
  rider:
  desfake:
  urgal:
  sonic:
  forcefield:
  chatclose:
  upi:
  tower:
  endermage:
  binladem:
  tpall:
  deshfire:
  gladiator:
  spiderman:
  formulario:
  inv:
  c4:
  trocador:
  phantom:
  hotpotato:
  tell:
  goku:
  ban:
  clear:
  kick:
  thresh:
  fly:
  efeitos:
  efeito1:
  efeito2:
  efeito3:
  efeito4:
  efeito5:
  efeito6:
  efeito7:
  efeito8:
  removerefeito:
  morf:
  vida:
  surprise:
  check:
  recraft:
  head:
  togglepvp:
  sopa:
  ghoul:
  hulk:
  viking:
  grenadier:
  ebola:
  fireman:
  flash:
  sniper:
  switcher:
  milkman:
  lobisomen:
  kits:
  kits2:
  warps:
  menu:
  ryu:
  cactus:
  wither:
  reaper:
  grappler:
  thor:
  camel:
  help:
  backpacker:
  netherman:
  launcher:
  ironman:
  nofall:
  leopardo:
  indio:
  fujao:
  report:
  poseidon:
  frosty:
  ninja:
  build:
  unban:
  fisherman:
  tag:
  titan:
  resouper:
  suicide:
  bc:
  specialist:
  admin:
  kill:
  stomper:
  req:
  checkpoint:
  infernor:
  youtuber:
  kangaroo:
  gm:
  creditos:
  setfps:
  critical:
  setchallenge:
  setspawn:
  spawn:
  fps:
  challenge:
  resetkit:
  cc:
  tp:
  barbarian:
  crash:
  setmain:
  monk:
  main:
  rdm:
  mdr:
  setmdr:
  setrdm: